// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNY9pPbwYh77gGm6-zJz2bVWbLqng2H50',
    appId: '1:1074635639605:android:da3ad1e2b444192aef9a7c',
    messagingSenderId: '1074635639605',
    projectId: 'arteria-cc308',
    storageBucket: 'arteria-cc308.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfPOQoE8kves9vY0aAn82-jPFhbwgAnh0',
    appId: '1:1074635639605:ios:1a6337dbf6b89e3fef9a7c',
    messagingSenderId: '1074635639605',
    projectId: 'arteria-cc308',
    storageBucket: 'arteria-cc308.firebasestorage.app',
    androidClientId: '1074635639605-n3pi09i2vvqnsdlap4qnhftnmr38p2bg.apps.googleusercontent.com',
    iosClientId: '1074635639605-bqrfl0btom00ak5vjbujbfut50r4c5f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.arteria',
  );

}